#!/usr/bin/env bash

# Copyright © 2026 <https://github.com/technosf>
# SPDX-FileCopyrightText: © 2026 <https://github.com/technosf>
#
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e

flatpak-builder --force-clean --user --install build-dir io.github.tuner_labs.tuner.yml
